-- =============================================================================
-- Script de Migración: Plazas, Sorteos y Rangos de Premio
-- Descripción: Crea las tablas CNL_PLAZAS, CNL_SORTEOS, CNL_RANGOS_PREMIO
--              y actualiza TRP_BOLETAS para soportar el modelo de plazas
--              con códigos seguros y sorteos consecutivos.
-- =============================================================================

-- 1. TABLA CNL_PLAZAS
-- Cada aplicación tiene un codigo_seguro único asignado desde la web.
-- =============================================================================
BEGIN
    EXECUTE IMMEDIATE '
    CREATE TABLE CNL_PLAZAS (
        ID_PLAZA       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        CODIGO_SEGURO  VARCHAR2(50 BYTE) NOT NULL,
        NOMBRE         VARCHAR2(100 BYTE) NOT NULL,
        ESTADO         VARCHAR2(20 BYTE) DEFAULT ''ACTIVO'',
        FECHA_CREACION TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
        CONSTRAINT UK_PLAZAS_CODIGO UNIQUE (CODIGO_SEGURO)
    )';
    DBMS_OUTPUT.PUT_LINE('Tabla CNL_PLAZAS creada.');
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = -955 THEN
            DBMS_OUTPUT.PUT_LINE('Tabla CNL_PLAZAS ya existe.');
        ELSE
            RAISE;
        END IF;
END;
/

-- 2. TABLA CNL_SORTEOS
-- Cada sorteo pertenece a una plaza y tiene un consecutivo automático.
-- =============================================================================
BEGIN
    EXECUTE IMMEDIATE '
    CREATE TABLE CNL_SORTEOS (
        ID_SORTEO     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        ID_PLAZA      NUMBER,
        NOMBRE_SORTEO VARCHAR2(150 BYTE) NOT NULL,
        FECHA_INICIO  DATE,
        FECHA_FIN     DATE,
        ESTADO        VARCHAR2(20 BYTE) DEFAULT ''ACTIVO'',
        CONSTRAINT FK_SORTEO_PLAZA FOREIGN KEY (ID_PLAZA)
            REFERENCES CNL_PLAZAS(ID_PLAZA)
    )';
    DBMS_OUTPUT.PUT_LINE('Tabla CNL_SORTEOS creada.');
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = -955 THEN
            DBMS_OUTPUT.PUT_LINE('Tabla CNL_SORTEOS ya existe.');
        ELSE
            RAISE;
        END IF;
END;
/

-- 3. TABLA CNL_RANGOS_PREMIO
-- Rangos de números premiados asociados a cada sorteo.
-- =============================================================================
BEGIN
    EXECUTE IMMEDIATE '
    CREATE TABLE CNL_RANGOS_PREMIO (
        ID_RANGO        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        ID_SORTEO       NUMBER NOT NULL,
        RANGO_INICIAL   NUMBER NOT NULL,
        RANGO_FINAL     NUMBER NOT NULL,
        MENSAJE_PREMIO  VARCHAR2(500 BYTE),
        PRIORIDAD       NUMBER DEFAULT 1 NOT NULL,
        ESTADO          VARCHAR2(20 BYTE) DEFAULT ''ACTIVO'',
        FECHA_VIGENCIA  DATE,
        CONSTRAINT FK_RANGO_SORTEO FOREIGN KEY (ID_SORTEO)
            REFERENCES CNL_SORTEOS(ID_SORTEO),
        CONSTRAINT UK_RANGO_NUMEROS UNIQUE (ID_SORTEO, RANGO_INICIAL, RANGO_FINAL)
    )';
    DBMS_OUTPUT.PUT_LINE('Tabla CNL_RANGOS_PREMIO creada.');
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = -955 THEN
            DBMS_OUTPUT.PUT_LINE('Tabla CNL_RANGOS_PREMIO ya existe.');
        ELSE
            RAISE;
        END IF;
END;
/

-- 4. TABLA TRP_BOLETAS — Verificar/Actualizar
-- Asegura que la FK apunte a CNL_SORTEOS y que LOTE_ORIGEN exista.
-- =============================================================================
BEGIN
    EXECUTE IMMEDIATE '
    CREATE TABLE TRP_BOLETAS (
        ID_BOLETA         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        ID_SORTEO         NUMBER,
        NUMERO_BOLETA     VARCHAR2(20 BYTE) NOT NULL,
        NUMEROS_OPORTUNIDADES VARCHAR2(500 BYTE),
        QR_TOKEN          VARCHAR2(100 BYTE) NOT NULL,
        ESTADO_REDENCION  VARCHAR2(20 BYTE) DEFAULT ''NO_CONSULTADA'',
        FECHA_GENERACION  TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
        LOTE_ORIGEN       VARCHAR2(50 BYTE),
        CONSTRAINT UK_BOLETA_QR UNIQUE (QR_TOKEN),
        CONSTRAINT FK_BOLETA_SORTEO FOREIGN KEY (ID_SORTEO)
            REFERENCES CNL_SORTEOS(ID_SORTEO)
    )';
    DBMS_OUTPUT.PUT_LINE('Tabla TRP_BOLETAS creada.');
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = -955 THEN
            DBMS_OUTPUT.PUT_LINE('Tabla TRP_BOLETAS ya existe. Verificando columnas...');
            -- Agregar LOTE_ORIGEN y NUMEROS_OPORTUNIDADES si no existen
            BEGIN
                EXECUTE IMMEDIATE 'ALTER TABLE TRP_BOLETAS ADD (LOTE_ORIGEN VARCHAR2(50 BYTE))';
                DBMS_OUTPUT.PUT_LINE('  Columna LOTE_ORIGEN agregada.');
            EXCEPTION
                WHEN OTHERS THEN
                    IF SQLCODE = -1430 THEN
                        DBMS_OUTPUT.PUT_LINE('  Columna LOTE_ORIGEN ya existe.');
                    ELSE
                        RAISE;
                    END IF;
            END;
            BEGIN
                EXECUTE IMMEDIATE 'ALTER TABLE TRP_BOLETAS ADD (NUMEROS_OPORTUNIDADES VARCHAR2(500 BYTE))';
                DBMS_OUTPUT.PUT_LINE('  Columna NUMEROS_OPORTUNIDADES agregada.');
            EXCEPTION
                WHEN OTHERS THEN
                    IF SQLCODE = -1430 THEN
                        DBMS_OUTPUT.PUT_LINE('  Columna NUMEROS_OPORTUNIDADES ya existe.');
                    ELSE
                        RAISE;
                    END IF;
            END;
        ELSE
            RAISE;
        END IF;
END;
/

-- 5. TABLA TRD_CONSULTAS_QR — Auditoría de escaneos (si no existe)
-- =============================================================================
BEGIN
    EXECUTE IMMEDIATE '
    CREATE TABLE TRD_CONSULTAS_QR (
        ID_CONSULTA      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        ID_BOLETA        NUMBER NOT NULL,
        IP_DISPOSITIVO   VARCHAR2(50 BYTE),
        AGENTE_USUARIO   VARCHAR2(500 BYTE),
        MENSAJE_MOSTRADO VARCHAR2(500 BYTE),
        FECHA_CONSULTA   TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
        CONSTRAINT FK_CONSULTA_BOLETA FOREIGN KEY (ID_BOLETA) 
            REFERENCES TRP_BOLETAS(ID_BOLETA)
    )';
    DBMS_OUTPUT.PUT_LINE('Tabla TRD_CONSULTAS_QR creada.');
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = -955 THEN
            DBMS_OUTPUT.PUT_LINE('Tabla TRD_CONSULTAS_QR ya existe.');
        ELSE
            RAISE;
        END IF;
END;
/

-- 6. TABLA AUD_INTENTOS_QR — Auditoría de escaneos fraudulentos (si no existe)
-- =============================================================================
BEGIN
    EXECUTE IMMEDIATE '
    CREATE TABLE AUD_INTENTOS_QR (
        ID_INTENTO        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        QR_TOKEN_INTENTADO VARCHAR2(100 BYTE),
        IP_ORIGEN         VARCHAR2(50 BYTE),
        MOTIVO_RECHAZO    VARCHAR2(500 BYTE),
        FECHA_INTENTO     TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP
    )';
    DBMS_OUTPUT.PUT_LINE('Tabla AUD_INTENTOS_QR creada.');
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = -955 THEN
            DBMS_OUTPUT.PUT_LINE('Tabla AUD_INTENTOS_QR ya existe.');
        ELSE
            RAISE;
        END IF;
END;
/

-- 7. SEED: Plaza de ejemplo para pruebas
-- =============================================================================
BEGIN
    INSERT INTO CNL_PLAZAS (CODIGO_SEGURO, NOMBRE, ESTADO)
    VALUES ('PLAZA-TEST-001', 'Plaza Demo Pruebas', 'ACTIVO');
    DBMS_OUTPUT.PUT_LINE('Plaza demo insertada: PLAZA-TEST-001');
EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
        DBMS_OUTPUT.PUT_LINE('Plaza demo PLAZA-TEST-001 ya existe.');
END;
/

COMMIT;
